name: markdown-mdspell

on:
  push:
    branches-ignore:
      - main
    paths:
      - "**.md"
      - .github/workflows/markdown-mdspell.yml
      - .spelling

permissions: read-all

jobs:
  markdown-mdspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          # renovate: datasource=github-tags depName=nodejs/node versioning=node
          node-version: 20

      - name: Install markdown-spellcheck
        run: npm install -g markdown-spellcheck

      - name: Run mdspell
        run: |
          set -euxo pipefail
          find . -type f \( -name "*.md" ! -name "CHANGELOG.md" \) -print0 | xargs -0 --max-args=1 mdspell --ignore-numbers --ignore-acronyms --report --en-gb {} \;
